name: build

on:
  push:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - run: |
          sh generate.sh
          rm dist/.gitignore
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: generate
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
      - uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          prerelease: true
