name: build

on:
  push:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - id: build
        uses: docker/build-push-action@v6
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=local,dest=dist/
          provenance: false
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: generate
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/
      - uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          prerelease: true
